import "server-only";
import { supabaseAdmin } from "@/lib/supabase/admin";

/**
 * Order writes, via the `place_order` Postgres function.
 *
 * The RPC is the whole transaction boundary: it inserts the order, its items,
 * and reserves stock atomically. Doing this from the client in three round trips
 * would let a crash leave a paid order with no items, or stock reserved for an
 * order that never existed.
 */

/**
 * One requested line.
 *
 * NOT priced by the caller: `place_order` looks every line up in `products` and
 * uses that price. `unitPrice`/`lineTotal` are what the browser believed and are
 * sent for the record only — the RPC discards them.
 */
export interface ICreateOrderLine {
  slug: string;
  name: string;
  color: string;
  size: string;
  /** Human-readable variant, e.g. "Sand · M". Stored for display on the order. */
  variantLabel: string;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
}

export interface ICreateOrderInput {
  customerName: string;
  email: string;
  phone?: string;
  addressLine1: string;
  addressLine2?: string;
  city: string;
  province: string;
  postalCode: string;
  country: string;
  deliveryMethod: string;
  deliveryLabel: string;
  paymentMethod: string;
  itemCount: number;
  subtotal: number;
  shipping: number;
  discount: number;
  total: number;
  currency: string;
  promoCode?: string;
  lines: ICreateOrderLine[];
}

/**
 * Either the order landed, or one variant sold out from under the customer.
 * Any other failure throws — callers cannot do anything useful with a
 * connection error beyond showing the generic message.
 */
export type CreateOrderResult =
  | { ok: true; id: string; reference: string; amounts: IOrderAmounts }
  | { ok: false; outOfStock: string };

/** What the database actually charged, computed from server-held prices. */
export interface IOrderAmounts {
  itemCount: number;
  subtotal: number;
  shipping: number;
  discount: number;
  total: number;
  currency: string;
}

/** SQLSTATE `place_order` raises when a variant has too little explicit stock. */
const CHECK_VIOLATION = "23514";
const OUT_OF_STOCK_PREFIX = "OUT_OF_STOCK:";

/**
 * Insert an order and reserve its stock.
 *
 * The reference is generated by the database — never send one, or two
 * concurrent checkouts can collide on it. The same applies to the money: the
 * amounts below are sent so the request records what the customer was shown,
 * but `place_order` re-derives every one of them and returns what it charged.
 */
export async function createOrder(
  input: ICreateOrderInput,
): Promise<CreateOrderResult> {
  const { data, error } = await supabaseAdmin.rpc("place_order", {
    p_order: {
      customer_name: input.customerName,
      email: input.email,
      phone: input.phone ?? null,
      address_line1: input.addressLine1,
      address_line2: input.addressLine2?.trim() ? input.addressLine2 : null,
      city: input.city,
      province: input.province,
      postal_code: input.postalCode,
      country: input.country,
      delivery_method: input.deliveryMethod,
      delivery_label: input.deliveryLabel,
      payment_method: input.paymentMethod,
      item_count: input.itemCount,
      subtotal: input.subtotal,
      shipping: input.shipping,
      discount: input.discount,
      total: input.total,
      currency: input.currency,
      promo_code: input.promoCode?.trim() ? input.promoCode : null,
    },
    p_items: input.lines.map((line) => ({
      slug: line.slug,
      name: line.name,
      color: line.color,
      size: line.size,
      variant_label: line.variantLabel,
      quantity: line.quantity,
      unit_price: line.unitPrice,
      line_total: line.lineTotal,
    })),
  });

  if (error) {
    if (
      error.code === CHECK_VIOLATION &&
      error.message.includes(OUT_OF_STOCK_PREFIX)
    ) {
      const name = error.message
        .slice(error.message.indexOf(OUT_OF_STOCK_PREFIX) + OUT_OF_STOCK_PREFIX.length)
        .trim();
      return { ok: false, outOfStock: name };
    }
    throw error;
  }

  // `place_order` is declared `returns table(...)`, so PostgREST hands back a
  // one-row array rather than an object.
  const row = data?.[0];
  if (!row) {
    throw new Error("place_order returned no row.");
  }

  return {
    ok: true,
    id: row.order_id,
    reference: row.reference,
    // Server-computed, not echoed input. If these differ from what was sent,
    // the client's arithmetic was wrong (or tampered with) and these win.
    amounts: {
      itemCount: row.item_count,
      subtotal: row.subtotal,
      shipping: row.shipping,
      discount: row.discount,
      total: row.total,
      currency: row.currency,
    },
  };
}
